# **Concrete Strength Prediction**
For concrete strength prediction here we have used 3 algorithms:

1.Linear Regression

2.Decision Tree Regressor

3.Random Forest Regressor

By using the above algorithms, we will train our model by providing training data and once the model will be trained, we will perform prediction.
After prediction, we will evaluate the performance of these algorithmns by error check and accuracy check.


### Steps been followed are as:
Step 1:Data Preprocessing

Step 2: Data training

Step 3: Model Creation

Step 4: Performance Evaluation



## Step 1- Data Preprocessing:

In [1]:
#importing pandas library to read data.
import pandas as pd

In [2]:
#loading data
data=pd.read_csv('./DataSets/concrete_data.csv')
data

Cement  Blast Furnace Slag  Fly Ash  Water  Superplasticizer  \
0      540.0                 0.0      0.0  162.0               2.5   
1      540.0                 0.0      0.0  162.0               2.5   
2      332.5               142.5      0.0  228.0               0.0   
3      332.5               142.5      0.0  228.0               0.0   
4      198.6               132.4      0.0  192.0               0.0   
...      ...                 ...      ...    ...               ...   
1025   276.4               116.0     90.3  179.6               8.9   
1026   322.2                 0.0    115.6  196.0              10.4   
1027   148.5               139.4    108.6  192.7               6.1   
1028   159.1               186.7      0.0  175.6              11.3   
1029   260.9               100.5     78.3  200.6               8.6   

      Coarse Aggregate  Fine Aggregate  Age  Strength  
0               1040.0           676.0   28     79.99  
1               1055.0           676.0   28     61.89  
2                932.0           594.0  270     40.27  
3                932.0           594.0  365     41.05  
4                978.4           825.5  360     44.30  
...                ...             ...  ...       ...  
1025             870.1           768.3   28     44.28  
1026             817.9           813.4   28     31.18  
1027             892.4           780.0   28     23.70  
1028             989.6           788.9   28     32.77  
1029             864.5           761.5   28     32.40  

[1030 rows x 9 columns]

In [3]:
#To view first 5 rows of the dataset.
data.head()

Cement  Blast Furnace Slag  Fly Ash  Water  Superplasticizer  \
0   540.0                 0.0      0.0  162.0               2.5   
1   540.0                 0.0      0.0  162.0               2.5   
2   332.5               142.5      0.0  228.0               0.0   
3   332.5               142.5      0.0  228.0               0.0   
4   198.6               132.4      0.0  192.0               0.0   

   Coarse Aggregate  Fine Aggregate  Age  Strength  
0            1040.0           676.0   28     79.99  
1            1055.0           676.0   28     61.89  
2             932.0           594.0  270     40.27  
3             932.0           594.0  365     41.05  
4             978.4           825.5  360     44.30

In [4]:
#To view last 5 rows of the dataset.
data.tail()

Cement  Blast Furnace Slag  Fly Ash  Water  Superplasticizer  \
1025   276.4               116.0     90.3  179.6               8.9   
1026   322.2                 0.0    115.6  196.0              10.4   
1027   148.5               139.4    108.6  192.7               6.1   
1028   159.1               186.7      0.0  175.6              11.3   
1029   260.9               100.5     78.3  200.6               8.6   

      Coarse Aggregate  Fine Aggregate  Age  Strength  
1025             870.1           768.3   28     44.28  
1026             817.9           813.4   28     31.18  
1027             892.4           780.0   28     23.70  
1028             989.6           788.9   28     32.77  
1029             864.5           761.5   28     32.40

In [5]:
#converting data into int datatype to avoid errors below.
data=data.astype(int)
data.head()

Cement  Blast Furnace Slag  Fly Ash  Water  Superplasticizer  \
0     540                   0        0    162                 2   
1     540                   0        0    162                 2   
2     332                 142        0    228                 0   
3     332                 142        0    228                 0   
4     198                 132        0    192                 0   

   Coarse Aggregate  Fine Aggregate  Age  Strength  
0              1040             676   28        79  
1              1055             676   28        61  
2               932             594  270        40  
3               932             594  365        41  
4               978             825  360        44

In [6]:
#To view non-null, dtype, memory usage & range of the dataset.
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Cement              1030 non-null   int32
 1   Blast Furnace Slag  1030 non-null   int32
 2   Fly Ash             1030 non-null   int32
 3   Water               1030 non-null   int32
 4   Superplasticizer    1030 non-null   int32
 5   Coarse Aggregate    1030 non-null   int32
 6   Fine Aggregate      1030 non-null   int32
 7   Age                 1030 non-null   int32
 8   Strength            1030 non-null   int32
dtypes: int32(9)
memory usage: 36.3 KB


In [7]:
#To view different columns of the dataset.
data.columns

Index(['Cement', 'Blast Furnace Slag', 'Fly Ash', 'Water', 'Superplasticizer',
       'Coarse Aggregate', 'Fine Aggregate', 'Age', 'Strength'],
      dtype='object')

In [8]:
#to view statistical summary of all numerical columns of the dataset.
data.describe()

Cement  Blast Furnace Slag      Fly Ash        Water  \
count  1030.000000         1030.000000  1030.000000  1030.000000   
mean    280.933981           73.762136    54.046602   181.279612   
std     104.585096           86.170344    63.856175    21.465127   
min     102.000000            0.000000     0.000000   121.000000   
25%     192.250000            0.000000     0.000000   164.000000   
50%     272.500000           22.000000     0.000000   185.000000   
75%     350.000000          142.750000   118.000000   192.000000   
max     540.000000          359.000000   200.000000   247.000000   

       Superplasticizer  Coarse Aggregate  Fine Aggregate          Age  \
count       1030.000000       1030.000000     1030.000000  1030.000000   
mean           5.938835        972.657282      773.300971    45.662136   
std            5.831214         77.707820       80.122250    63.169912   
min            0.000000        801.000000      594.000000     1.000000   
25%            0.000000        932.000000      730.500000     7.000000   
50%            6.000000        968.000000      779.000000    28.000000   
75%           10.000000       1029.000000      824.000000    56.000000   
max           32.000000       1145.000000      992.000000   365.000000   

          Strength  
count  1030.000000  
mean     35.319417  
std      16.705298  
min       2.000000  
25%      23.000000  
50%      34.000000  
75%      45.750000  
max      82.000000

In [9]:
#check for any null values in the dataset.
data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [10]:
data.isnull().sum().sum()

0

The data is clean i.e. no missing or inappropriate values found.

## Step 2 Data training:

In [11]:
# Import train_test_split from sklearn.model_selection
from sklearn.model_selection import train_test_split
# Here, X is the data which will have features and y will have our target i.e. strength.
X=data[['Cement', 'Blast Furnace Slag', 'Fly Ash', 'Water', 'Superplasticizer',
       'Coarse Aggregate', 'Fine Aggregate', 'Age']]  
y=data['Strength']

In [12]:
# Split data into training data and testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=500) 
#Ratio used for splitting training and testing data is 8:2 respectively.

In [13]:
#to view length of training data.
len(X_train)

824

In [14]:
#to view length of testing data.
len(X_test)

206

## Step 3- Model Creation:

### **Linear Regression**

In [15]:
# Importing linear regression model
from sklearn.linear_model import LinearRegression 
reg1 = LinearRegression()

In [16]:
# Fitting data into the model.
reg1.fit(X_train, y_train) 

LinearRegression()

In [17]:
# Making predictions 
pred1 = reg1.predict(X_test) 

In [18]:
pred1

array([50.56059863, 50.21047465, 38.04490151, 38.3156941 , 29.56284962,
       30.75103197, 45.77586631, 41.26107651, 10.12486307, 25.90578348,
       29.06438418, 52.90488571, 23.38332453, 38.85004576, 31.67111523,
       33.6059699 , 33.81951902, 28.59953336, 23.90433358, 38.50926211,
       27.36857007, 29.78202169, 34.44691637, 28.86872032, 53.34901389,
       22.62191785, 32.89970566, 24.14420269, 46.52063587, 47.7600064 ,
       22.62716035, 39.71657815, 31.66186304, 36.60207658, 26.95429446,
       32.83380528, 53.4294485 , 31.90799494, 36.18330131, 27.55391628,
       26.70728477, 53.75476327, 39.61124477, 32.34632769, 36.07424462,
       45.69389389, 47.26739585, 24.26392353, 51.36838682, 23.44953657,
       33.14181395, 33.623664  , 50.43969879, 55.68068685, 19.78192164,
       36.1732422 , 23.615643  , 42.81836722, 78.09013094, 30.62774546,
       33.78173302, 53.34901389, 28.5255484 , 67.26975627, 53.34901389,
       21.19145072, 22.51136896, 20.20858345, 44.98420526, 52.51

In [19]:
len(pred1)

206

In [20]:
print("Accuracy of the LinearRegression model comes to be: \n ") 
print(reg1.score(X_train,y_train))

Accuracy of the LinearRegression model comes to be: 
 
0.6136179224215672


## **Decision Tree Regressor**


In [21]:
# Importing decision tree regressor 
from sklearn.tree import DecisionTreeRegressor 
reg2 = DecisionTreeRegressor() 

In [22]:
#Fitting data into the model.
reg2.fit(X_train, y_train) 

DecisionTreeRegressor()

In [23]:
# Making predictions on Test data 
pred2 = reg2.predict(X_test) 

In [24]:
pred2

array([44.        , 65.        , 26.        , 19.        , 22.        ,
       29.        , 37.        , 33.        , 13.        , 25.        ,
       37.        , 33.        , 13.        , 31.        , 22.        ,
       30.        , 29.        , 50.        , 26.        , 57.        ,
       40.        , 12.        , 34.        , 38.        , 36.        ,
       14.        , 26.        , 13.        , 43.        , 59.        ,
       25.        , 42.        , 40.        , 40.        , 40.        ,
       40.        , 67.        , 44.        , 43.        , 15.        ,
       17.        , 54.        , 46.        , 43.        , 19.        ,
       65.        , 66.        , 15.        , 67.        , 19.        ,
       39.        , 30.        , 42.        , 60.        , 22.        ,
        9.        , 24.        , 43.        , 71.        , 36.        ,
       33.        , 36.        , 29.        , 43.        , 36.        ,
       15.        , 25.        , 14.        , 24.        , 25.  

In [25]:
print("Accuracy of the Decision Tree Regressor  model comes to be: \n ") 
print(reg2.score(X_train,y_train))

Accuracy of the Decision Tree Regressor  model comes to be: 
 
0.9956195447608779


## **Random Forest Regressor**

In [26]:
#Importing random forest regressor 
from sklearn.ensemble import RandomForestRegressor 
reg3 = RandomForestRegressor(n_estimators=100) 

In [27]:
# Fitting data into the model.
reg3.fit(X_train, y_train) 

RandomForestRegressor()

In [28]:
#making predictions.
pred3 = reg3.predict(X_test) 
pred3

array([49.45      , 62.345     , 31.54      , 18.16      , 27.36      ,
       29.03      , 38.29      , 33.24      ,  8.28      , 29.37      ,
       35.5       , 33.03      , 14.53      , 37.68      , 21.24333333,
       32.91      , 32.47      , 44.47      , 26.71      , 52.11      ,
       29.04      , 14.91333333, 36.18      , 38.66      , 42.42583333,
       15.47      , 29.6       , 13.66      , 50.73      , 60.23      ,
       24.1       , 46.99      , 37.35      , 43.16      , 35.53      ,
       40.95      , 64.66      , 42.59      , 39.67      , 16.        ,
       16.88      , 54.078     , 44.51      , 40.86      , 16.48      ,
       60.3       , 63.585     , 15.05      , 58.08      , 22.73      ,
       36.94      , 32.79      , 35.1725    , 60.22      , 25.14      ,
       16.51      , 23.76      , 48.3       , 69.65      , 37.7       ,
       29.54      , 42.42583333, 36.04      , 42.07      , 42.42583333,
       15.26      , 27.53      , 14.24      , 26.63      , 36.02

In [29]:
print("Accuracy of the Random Forest Regressor  model comes to be: \n ") 
print(reg3.score(X_train,y_train))

Accuracy of the Random Forest Regressor  model comes to be: 
 
0.983387060140012


## Step 4: Performance Evaluation:

In [30]:
import numpy as np
from sklearn.metrics import mean_squared_error
print("Model\t\t\t RootMeanSquareError \t\t Accuracy of the model") 
print("""Linear Regression \t\t {:.4f} \t \t\t {:.4f}""".format(  np.sqrt(mean_squared_error(y_test, pred1)), reg1.score(X_train,y_train)))
print("""Decision Tree Regressor\t\t {:.4f} \t \t\t {:.4f}""".format(  np.sqrt(mean_squared_error(y_test, pred2)), reg2.score(X_train,y_train)))
print("""Random Forest Regressor\t\t {:.4f} \t \t\t {:.4f}""".format(  np.sqrt(mean_squared_error(y_test, pred3)), reg3.score(X_train,y_train)))

Model			 RootMeanSquareError 		 Accuracy of the model
Linear Regression 		 10.7989 	 		 0.6136
Decision Tree Regressor		 6.1652 	 		 0.9956
Random Forest Regressor		 5.4189 	 		 0.9834
