# COURSE:   PGP [AI&ML]

## Learner :  Chaitanya Kumar Battula
## Module  : Machine Learning
## Topic   : Obtain Cluster Centers In an Image

In [1]:
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

In [2]:
image = Image.open('tiger.png')

In [3]:
type(image)

PIL.PngImagePlugin.PngImageFile

In [4]:
image_array = np.asarray(image)

In [5]:
type(image_array)

numpy.ndarray

In [6]:
image_array

array([[[164, 160, 159],
        [165, 161, 160],
        [164, 163, 161],
        ...,
        [160, 128,  90],
        [158, 125,  90],
        [161, 128,  93]],

       [[164, 160, 159],
        [164, 160, 159],
        [163, 162, 160],
        ...,
        [164, 132,  94],
        [162, 129,  94],
        [157, 124,  89]],

       [[163, 159, 156],
        [164, 160, 157],
        [163, 162, 160],
        ...,
        [164, 132,  94],
        [162, 129,  94],
        [157, 124,  89]],

       ...,

       [[ 93,  94,  96],
        [ 93,  94,  96],
        [ 92,  93,  95],
        ...,
        [120, 116, 107],
        [121, 117, 108],
        [122, 118, 109]],

       [[ 93,  94,  96],
        [ 93,  94,  96],
        [ 92,  93,  95],
        ...,
        [120, 116, 107],
        [121, 117, 108],
        [122, 118, 109]],

       [[ 93,  94,  96],
        [ 93,  94,  96],
        [ 92,  93,  95],
        ...,
        [119, 115, 106],
        [121, 117, 108],
        [122, 118, 109]]

In [7]:
image_array.shape

(720, 1280, 3)

In [8]:
pixels = image_array.reshape(image_array.shape[0]*image_array.shape[1],image_array.shape[2])

In [9]:
pixels.shape

(921600, 3)

In [17]:
from sklearn.cluster import KMeans

In [18]:
kmeans = KMeans(n_clusters=16)

In [19]:
kmeans.fit(pixels)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=16, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [22]:
np.unique(kmeans.labels_)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int32)

In [21]:
kmeans.cluster_centers_

array([[107.66992733,  70.76513189,  44.6487037 ],
       [176.83626514, 177.42182726, 177.75152474],
       [ 52.65664172,  42.91961218,  37.01637878],
       [187.91375358,  85.09240688, 131.48209169],
       [ 70.33965171,  69.24545051,  58.50501292],
       [109.40662737, 118.49251826, 103.76665792],
       [230.71945687, 229.68423801, 229.92006397],
       [ 61.24746263, 126.57969602,  44.21746413],
       [ 94.54447561,  91.77133146,  83.15917134],
       [132.04115226, 136.31049847, 125.41401343],
       [203.72682357, 201.31332803, 199.92827533],
       [ 25.23456177,  19.49998344,  17.15403463],
       [212.20335965, 170.4047707 , 135.31335461],
       [177.03225375, 138.00652023, 102.91387419],
       [136.06671018, 110.13195903,  84.36128767],
       [154.42915019, 156.9097447 , 155.37369052]])

In [23]:
pixel_centroids = kmeans.labels_

In [24]:
cluster_centers = kmeans.cluster_centers_

In [26]:
final_image = np.zeros((pixel_centroids.shape[0],3))

In [28]:
final_image.shape

(921600, 3)

In [30]:
for cluster in range(16):
    final_image[pixel_centroids==cluster] = cluster_centers[cluster]

In [32]:
final_image.shape

(921600, 3)

In [33]:
final_image_view = final_image.reshape(image_array.shape[0],image_array.shape[1],3)

In [34]:
final_image_view.shape

(720, 1280, 3)

In [36]:
original_image = mpimg.imread('tiger.png')

In [37]:
final_image_view = Image.fromarray(np.uint8(final_image_view))

In [38]:
final_image_save = final_image_view.save('final_image_view_filter.png')